# Generated by Django 3.2.3 on 2021-05-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ('body_comp', '0001_initial'),
  ]

  operations = [
      migrations.RenameModel(
          old_name='WeightUnits',
          new_name='WeightUnit',
      ),
  ]
