# Generated by Django 3.2.3 on 2021-05-23 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
      ('body_comp', '0002_rename_weightunits_weightunit'),
  ]

  operations = [
      migrations.AddField(
          model_name='day',
          name='fit_user',
          field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
          preserve_default=False,
      ),
  ]
