# Generated by Django 3.2.3 on 2021-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('remesh', '0001_initial'),
  ]

  operations = [
      migrations.AlterField(
          model_name='message',
          name='date_time_sent',
          field=models.DateTimeField(),
      ),
      migrations.AlterField(
          model_name='thought',
          name='date_time_sent',
          field=models.DateTimeField(),
      ),
  ]
