# Generated by Django 3.2.3 on 2021-05-24 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
      ('remesh', '0003_day_fit_user'),
  ]

  operations = [
      migrations.CreateModel(
          name='Team',
          fields=[
              ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
              ('team_members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
          ],
      ),
  ]
