# Generated by Django 3.2.3 on 2021-05-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ('remesh', '0004_team'),
  ]

  operations = [
      migrations.RenameField(
          model_name='team',
          old_name='team_members',
          new_name='members',
      ),
  ]
