# Generated by Django 3.2.3 on 2021-05-24 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
      ('remesh', '0005_rename_team_members_team_members'),
  ]

  operations = [
      migrations.CreateModel(
          name='Conversion',
          fields=[
              ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
              ('title', models.CharField(max_length=250)),
              ('date', models.DateField()),
              ('start_time', models.TimeField()),
              ('duration', models.DurationField()),
              ('max_num_of_participants', models.PositiveIntegerField()),
              ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
              ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remesh.team')),
          ],
      ),
  ]
