# Generated by Django 3.2.3 on 2021-05-24 16:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
      ('remesh', '0006_conversion'),
  ]

  operations = [
      migrations.RenameModel(
          old_name='Conversion',
          new_name='Conversation',
      ),
  ]
