# Generated by Django 3.2.3 on 2021-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesh', '0009_auto_20210524_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='old_team', max_length=250),
            preserve_default=False,
        ),
    ]
