# Generated by Django 3.2.3 on 2021-05-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesh', '0010_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='start_time',
        ),
        migrations.AddField(
            model_name='conversation',
            name='start_date_time',
            field=models.DateTimeField(default='2020-01-01 01:01'),
            preserve_default=False,
        ),
    ]
